# Generated by Django 3.0.6 on 2020-05-31 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('contactNo', phonenumber_field.modelfields.PhoneNumberField(max_length=128, primary_key=True, region=None, serialize=False, unique=True, verbose_name='contactNo')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hKey', models.IntegerField(primary_key=True, serialize=False)),
                ('hName', models.CharField(max_length=50)),
                ('hAddress', models.CharField(max_length=100)),
                ('hContactNo', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('hEmailId', models.EmailField(max_length=254)),
                ('update_ts', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('sensorId', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('xCor', models.SmallIntegerField()),
                ('yCor', models.SmallIntegerField()),
                ('floorNo', models.SmallIntegerField()),
                ('physicalName', models.CharField(default='Unknown', max_length=50)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medapi.Hospital')),
            ],
        ),
        migrations.CreateModel(
            name='PubsubKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_key', models.CharField(max_length=100)),
                ('sub_key', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cName', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=1)),
                ('birthday', models.DateField(default=None)),
                ('occupation', models.CharField(max_length=50)),
                ('otpField', models.CharField(max_length=6)),
                ('cliUniqueNotifId', models.CharField(blank=True, max_length=500)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medapi.Hospital')),
                ('workLocation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medapi.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('operator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('oName', models.CharField(max_length=30)),
                ('opStatus', models.CharField(max_length=1)),
                ('opUniqueNotifId', models.CharField(max_length=500)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medapi.Hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('macId', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('rName', models.CharField(max_length=30)),
                ('direction', models.CharField(max_length=1)),
                ('rStatus', models.CharField(max_length=1)),
                ('robUniqueNotifId', models.CharField(max_length=500)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medapi.Hospital')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medapi.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('bedNumber', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('wardNumber', models.CharField(max_length=10)),
                ('pName', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=30)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medapi.Hospital')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medapi.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medapi.Hospital')),
                ('sensorId1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node1', to='medapi.Location')),
                ('sensorId2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node2', to='medapi.Location')),
            ],
        ),
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('requestId', models.BigAutoField(primary_key=True, serialize=False)),
                ('senMsg', models.CharField(max_length=1000)),
                ('recMsg', models.CharField(max_length=1000)),
                ('reqMsg', models.CharField(max_length=1000)),
                ('ordReqStatus', models.CharField(max_length=1)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('activated_ts', models.DateTimeField(null=True)),
                ('completed_ts', models.DateTimeField(null=True)),
                ('rlocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReceiverLocation', to='medapi.Location')),
                ('robot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medapi.Robot')),
                ('slocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SenderLocation', to='medapi.Location')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medapi.Operator')),
                ('rGeneratorClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medapi.Client')),
            ],
        ),
    ]
